// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP2_D6T7awreTQEqSjoXRv3370KJj8t-E',
    appId: '1:555027297027:web:e0f46e01568ac585466f36',
    messagingSenderId: '555027297027',
    projectId: 'notexted-be06f',
    authDomain: 'notexted-be06f.firebaseapp.com',
    storageBucket: 'notexted-be06f.firebasestorage.app',
    measurementId: 'G-D03P2F88GS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8LI-QJl2UpLHuaXn6Q4XbUK5ItwLTI0Y',
    appId: '1:555027297027:android:40c6af2f2127e60d466f36',
    messagingSenderId: '555027297027',
    projectId: 'notexted-be06f',
    storageBucket: 'notexted-be06f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6KnTUrdw_-CgXt0sFxoSFaC8CWJWXaFw',
    appId: '1:555027297027:ios:4fb051e1c3530a18466f36',
    messagingSenderId: '555027297027',
    projectId: 'notexted-be06f',
    storageBucket: 'notexted-be06f.firebasestorage.app',
    iosBundleId: 'com.example.notexted',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6KnTUrdw_-CgXt0sFxoSFaC8CWJWXaFw',
    appId: '1:555027297027:ios:4fb051e1c3530a18466f36',
    messagingSenderId: '555027297027',
    projectId: 'notexted-be06f',
    storageBucket: 'notexted-be06f.firebasestorage.app',
    iosBundleId: 'com.example.notexted',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP2_D6T7awreTQEqSjoXRv3370KJj8t-E',
    appId: '1:555027297027:web:699a001e1a96ceb4466f36',
    messagingSenderId: '555027297027',
    projectId: 'notexted-be06f',
    authDomain: 'notexted-be06f.firebaseapp.com',
    storageBucket: 'notexted-be06f.firebasestorage.app',
    measurementId: 'G-ZBYTKTK9FW',
  );
}
